version: '2'
services:
  web:
    restart: always
    image: meanapp
    container_name: meanjs
    networks:
    - slurm_slurm
    - dbnet
    - webnet
    ports:
     - "3000:3000"
     - "5858:5858"
     - "8080:8080"
     - "35729:35729"
    environment:
     - NODE_ENV=development
     - DB_1_PORT_27017_TCP_ADDR=db
    depends_on:
     - db
    volumes:
      - /tmp/results:/tmp/results
      - /tmp/analytics:/tmp/analytics
      - /tmp/datasets:/tmp/datasets
      - /tmp/dashboards:/tmp/dashboards
    volumes_from:
     - web-data
  web-data:
    image: meanapp
    networks:
    - webnet
    entrypoint: /bin/true
    volumes:
     - ./:/opt/mean.js
     - /opt/mean.js/node_modules
     - /opt/mean.js/public
     - /opt/mean.js/uploads
  db:
    image: mongo:3.2
    networks:
    - dbnet
    restart: always
    ports:
     - "27017:27017"
    volumes_from:
      - db-data
  db-data:
    image: mongo:3.2
    networks:
    - dbnet
    volumes:
      - /data/db
      - /var/lib/mongodb
      - /var/log/mongodb
    entrypoint: /bin/true

networks:
  slurm_slurm:
    external: true
  dbnet: 
    driver: bridge
  webnet:
    driver: bridge
